---
- hosts: all
  tasks:
    - name: deploy code
      git: repo=https://github.com/tomviner/github-hook-collector.git
           dest=/home/projadm/www/{{ domain }}/github-hook-collector/
           recursive=yes
           depth=1
           accept_hostkey=yes
    - name: install local django
      pip: name=/home/projadm/www/{{ domain }}/github-hook-collector/django state=present
    - name: install code
      pip: name=/home/projadm/www/{{ domain }}/github-hook-collector/ state=present
