---
- hosts: all
  tasks:
    - name: system deps
      apt: name={{ item }} state=installed
      apt: name=nginx state=installed
# add user
# useradd -m -s /bin/bash -p projadm projadm
    - name: add web group
      group: name=projadm state=present
    - name: add web user
      user: name=projadm group=projadm createhome=yes shell=/bin/bash
# nginx
# - new conf
    - name: nginx conf
      template: src=../templates/nginx.txt dest=/etc/nginx/sites-available/website
      notify:
          - reload nginx
# - sym link in
    - name: symlink new conf
      file: src=/etc/nginx/sites-available/website dest=/etc/nginx/sites-enabled/website state=link
# - remove default sym link
    - name: remove default symlink nginx conf
      file: path=/etc/nginx/sites-enabled/default state=absent
# - reload nginx
      notify:
          - reload nginx
  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded
